<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MikeRow\Bandano\NanoAPI;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class ServiceRegister extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ServiceRegister
     */
    public static function getRootAsServiceRegister(ByteBuffer $bb)
    {
        $obj = new ServiceRegister();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ServiceRegister
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getServiceName()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startServiceRegister(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return ServiceRegister
     */
    public static function createServiceRegister(FlatBufferBuilder $builder, $service_name)
    {
        $builder->startObject(1);
        self::addServiceName($builder, $service_name);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addServiceName(FlatBufferBuilder $builder, $serviceName)
    {
        $builder->addOffsetX(0, $serviceName, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endServiceRegister(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
