<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MikeRow\NanoPHP\NanoAPI;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class ServiceStop extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return ServiceStop
     */
    public static function getRootAsServiceStop(ByteBuffer $bb)
    {
        $obj = new ServiceStop();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return ServiceStop
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getServiceName()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return bool
     */
    public function getRestart()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startServiceStop(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return ServiceStop
     */
    public static function createServiceStop(FlatBufferBuilder $builder, $service_name, $restart)
    {
        $builder->startObject(2);
        self::addServiceName($builder, $service_name);
        self::addRestart($builder, $restart);
        $o = $builder->endObject();
        $builder->required($o, 4);  // service_name
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addServiceName(FlatBufferBuilder $builder, $serviceName)
    {
        $builder->addOffsetX(0, $serviceName, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addRestart(FlatBufferBuilder $builder, $restart)
    {
        $builder->addBoolX(1, $restart, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endServiceStop(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        $builder->required($o, 4);  // service_name
        return $o;
    }
}
