<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MikeRow\Bandano\NanoAPI;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class TopicConfirmation extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return TopicConfirmation
     */
    public static function getRootAsTopicConfirmation(ByteBuffer $bb)
    {
        $obj = new TopicConfirmation();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return TopicConfirmation
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return bool
     */
    public function getUnsubscribe()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    public function getOptions()
    {
        $obj = new TopicConfirmationOptions();
        $o = $this->__offset(6);
        return $o != 0 ? $obj->init($this->__indirect($o + $this->bb_pos), $this->bb) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startTopicConfirmation(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return TopicConfirmation
     */
    public static function createTopicConfirmation(FlatBufferBuilder $builder, $unsubscribe, $options)
    {
        $builder->startObject(2);
        self::addUnsubscribe($builder, $unsubscribe);
        self::addOptions($builder, $options);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addUnsubscribe(FlatBufferBuilder $builder, $unsubscribe)
    {
        $builder->addBoolX(0, $unsubscribe, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addOptions(FlatBufferBuilder $builder, $options)
    {
        $builder->addOffsetX(1, $options, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endTopicConfirmation(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
