<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MikeRow\NanoPHP\NanoAPI;

class TopicConfirmationTypeFilter
{
    const all = 0;
    const active = 1;
    const active_quorum = 2;
    const active_confirmation_height = 3;
    const inactive = 4;

    private static $names = array(
        TopicConfirmationTypeFilter::all=>"all",
        TopicConfirmationTypeFilter::active=>"active",
        TopicConfirmationTypeFilter::active_quorum=>"active_quorum",
        TopicConfirmationTypeFilter::active_confirmation_height=>"active_confirmation_height",
        TopicConfirmationTypeFilter::inactive=>"inactive",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
