<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace nanoapi;

class Block
{
    const NONE = 0;
    const BlockState = 1;
    const BlockOpen = 2;
    const BlockReceive = 3;
    const BlockSend = 4;
    const BlockChange = 5;

    private static $names = array(
        Block::NONE=>"NONE",
        Block::BlockState=>"BlockState",
        Block::BlockOpen=>"BlockOpen",
        Block::BlockReceive=>"BlockReceive",
        Block::BlockSend=>"BlockSend",
        Block::BlockChange=>"BlockChange",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
