<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace nanoapi;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class BlockState extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return BlockState
     */
    public static function getRootAsBlockState(ByteBuffer $bb)
    {
        $obj = new BlockState();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return BlockState
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getHash()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getAccount()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getPrevious()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getRepresentative()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getBalance()
    {
        $o = $this->__offset(12);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getLink()
    {
        $o = $this->__offset(14);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getLinkAsAccount()
    {
        $o = $this->__offset(16);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getSignature()
    {
        $o = $this->__offset(18);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getWork()
    {
        $o = $this->__offset(20);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return sbyte
     */
    public function getSubtype()
    {
        $o = $this->__offset(22);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : \nanoapi\BlockSubType::invalid;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startBlockState(FlatBufferBuilder $builder)
    {
        $builder->StartObject(10);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return BlockState
     */
    public static function createBlockState(FlatBufferBuilder $builder, $hash, $account, $previous, $representative, $balance, $link, $link_as_account, $signature, $work, $subtype)
    {
        $builder->startObject(10);
        self::addHash($builder, $hash);
        self::addAccount($builder, $account);
        self::addPrevious($builder, $previous);
        self::addRepresentative($builder, $representative);
        self::addBalance($builder, $balance);
        self::addLink($builder, $link);
        self::addLinkAsAccount($builder, $link_as_account);
        self::addSignature($builder, $signature);
        self::addWork($builder, $work);
        self::addSubtype($builder, $subtype);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addHash(FlatBufferBuilder $builder, $hash)
    {
        $builder->addOffsetX(0, $hash, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addAccount(FlatBufferBuilder $builder, $account)
    {
        $builder->addOffsetX(1, $account, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addPrevious(FlatBufferBuilder $builder, $previous)
    {
        $builder->addOffsetX(2, $previous, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addRepresentative(FlatBufferBuilder $builder, $representative)
    {
        $builder->addOffsetX(3, $representative, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addBalance(FlatBufferBuilder $builder, $balance)
    {
        $builder->addOffsetX(4, $balance, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addLink(FlatBufferBuilder $builder, $link)
    {
        $builder->addOffsetX(5, $link, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addLinkAsAccount(FlatBufferBuilder $builder, $linkAsAccount)
    {
        $builder->addOffsetX(6, $linkAsAccount, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addSignature(FlatBufferBuilder $builder, $signature)
    {
        $builder->addOffsetX(7, $signature, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addWork(FlatBufferBuilder $builder, $work)
    {
        $builder->addOffsetX(8, $work, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addSubtype(FlatBufferBuilder $builder, $subtype)
    {
        $builder->addSbyteX(9, $subtype, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endBlockState(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
