<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace nanoapi;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class TopicServiceStop extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return TopicServiceStop
     */
    public static function getRootAsTopicServiceStop(ByteBuffer $bb)
    {
        $obj = new TopicServiceStop();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return TopicServiceStop
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return bool
     */
    public function getUnsubscribe()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getBool($o + $this->bb_pos) : false;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startTopicServiceStop(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return TopicServiceStop
     */
    public static function createTopicServiceStop(FlatBufferBuilder $builder, $unsubscribe)
    {
        $builder->startObject(1);
        self::addUnsubscribe($builder, $unsubscribe);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param bool
     * @return void
     */
    public static function addUnsubscribe(FlatBufferBuilder $builder, $unsubscribe)
    {
        $builder->addBoolX(0, $unsubscribe, false);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endTopicServiceStop(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
